### ISSUE TITLE
Error during database migration 

### ISSUE THREAD

**Issue by chanukad24** [netbox-community/netbox-napalm#15]
**NetBox version**
3.5.3 

**Describe the bug**
Getting an error when try to run database migration after enable the plugin. Username is already set in the configuration.py

ERROR : 
django.core.exceptions.ImproperlyConfigured: Plugin netbox_napalm_plugin requires 'NAPALM_USERNAME' to be present in the PLUGINS_CONFIG section of configuration.py.

**To Reproduce**
1. Install Netbox 3.5.3
2. Install plugin "netbox_napalm_plugin"
3. Enable the plugin and set username and password in configuration.py
4. Run database migration

**Expected behavior**
Database migration completed with no errors.

**Screenshots**
![image](https://github.com/netbox-community/netbox-napalm/assets/136179008/95fad6ef-f33a-469a-a99c-70303d5e3f44)

**Comment by arthanson** [comment]
Old issue, closing out.
