### ISSUE TITLE
Add support for netbox version v3.6

### ISSUE THREAD

**Issue by bz-maldridge** [netbox-community/netbox-napalm#18]
**NetBox version**
Encountered the limitation during the upgrade to v3.6.0

**Describe the bug**

```
django.core.exceptions.ImproperlyConfigured: Plugin netbox_napalm_plugin requires NetBox maximum version 3.5.99.
```

**To Reproduce**
Attempt to install while using Netbox v3.6.0.

**Expected behavior**
Installation should succeed.

**Screenshots**
N/A

**Additional context**
Mostly just filing this bug to prompt a release and capture any blocking items that make the NAPALM plugin actually incompatible with v3.6 instead of pessimistically incompatible.

**Comment by ryanmerolle** [comment]
It’s not a bug, but as you said compatibility for 3.6 still needed an issue to track.

**Comment by the-maldridge** [comment]
Anything I can do to assist with the upgrade?

**Comment by robertlynch3** [comment]
3.6 support added in #19
