### ISSUE TITLE
Plugin name in docs is wrong

### ISSUE THREAD

**Issue by tobicodesstuff** [netbox-community/netbox-napalm#2]
**NetBox version**
v3.4.5 (edited the Version requirements locally)

**Describe the bug**
The plugin name in configuration.py PLUGINS is incorrect.

```
PLUGINS = [
    'Napalm'
]
```

**To Reproduce**
-

**Expected behavior**
```
PLUGINS = [
    'netbox_napalm_plugin'
]
```

**Screenshots**
-

**Additional context**
-

**Comment by arthanson** [comment]
thanks. should be fixed now.
