### ISSUE TITLE
No module named 'netbox_napalm_plugin'

### ISSUE THREAD

**Issue by kozlooo** [netbox-community/netbox-napalm#24]
**NetBox version**
What version of NetBox are you currently running? 
3.6.3
**Describe the bug**

**To Reproduce**
1. Follow netbox official documentation and prepare docker file for netbox installation with napalm plugin
2. Build docker image
4. Add to custom HELM chart init commands for migration
5. Enable napalm plugin
6. Try to run it 

**Expected behavior**
Netbox will be running as it was with other plugins

**Additional context**
Hi! I am trying to install netbox-napalm-plugin but without success. We have custom helm chart for netbox and it is deployed in k8s environment. Netbox deployment consist of netbox pod and worker pod which works as init container. Netbox is working fine with other plugins, have several installed on sysytem,, but when I try to add napalm plugin, it does not start up, netbox error 
ModuleNotFoundError: No module named 'netbox_napalm_plugin'. I followed napalm documentation and added migrate command to init container, but it is not working.
I thought that maybe issue is in python env, but it is not, tried to install venv and in usual pip (for troubleshooting reasons)

**Comment by gormur** [comment]
@kozlooo Please be aware that the string needed in plugin_requirements.txt is different from the one needed in configuration/plugins.py. **Notice dash and underscore.**

- netbox-napalm-plugin in plugin_requirements.txt
- netbox_napalm_plugin in configuration/plugins.py

**Comment by arthanson** [comment]
@kozlooo Does the above solve your issue?  Looking to close this ticket.
