### ISSUE TITLE
Error when trying to add platform config in 3.5 - serializernotfound

### ISSUE THREAD

**Issue by sliddjur** [netbox-community/netbox-napalm#7]
**NetBox version**
3.5

**Describe the bug**
Trying to add napalm platform config
I was thrown this error:
```
<class 'netbox.api.exceptions.SerializerNotFound'>
Could not determine serializer for netbox_napalm_plugin.NapalmPlatformConfig with prefix ''
```

**To Reproduce**
In netbox gui, go to napalm plugin, press add, chose your platform.
I tested with driver `nxos_ssh` and napalm arguments `{"read_timeout_override": 60}`

**Expected behavior**
It should work

**Screenshots**
![image](https://user-images.githubusercontent.com/10002057/235125100-89ed4db4-eef9-4e15-8d8f-9fa605a85c60.png)

**Comment by arthanson** [comment]
@sliddjur Thank you for the bug report, this should hopefully be fixed now with a new release on pypi v0.1.1.  There were some missing files in the v0.1.0 release.  Please let me know if any issues.
