### ISSUE TITLE
Static files missing for device napalm ui tabs

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox-napalm#8]
**NetBox version**
3.5.0

**NetBox-NAPALM version**
0.1.1

**Describe the bug**
Static files missing from device napalm ui tabs:

**To Reproduce**
1. Create a napalm platform linking
2. Click on a device with said platform
3. Click any of the NAPALM tabs in the UI

**Expected behavior**
UI page viewable

**Screenshots**
![Capture](https://user-images.githubusercontent.com/9010275/235312994-53abafba-5282-4550-a8f3-8a41fcab9c62.PNG)

**Additional context**

**Comment by arthanson** [comment]
fixed, release 0.1.2 I had the old files in my staticfiles dir from development so didn't see this, nuked my old files and was able to repro - thanks for catching this.
